site_name: MCHhammer
repo_url: https://github.com/etorkia/MCHammer.jl
site_description: Monte-Carlo Simulation for Julia
site_author: Eric Torkia
theme: readthedocs

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
  - mdx_math  # For LaTeX

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

nav:
  - Overview: index.md
  - User Manual:
    - Monte-Carlo Simulation: manual/1_functions.md
    - Distribution Fitting: manual/distribution_fitting.md
    - Charting & Analyzing: manual/2_charts.md
    - Time Series:
      - Random & Probability Methods: manual/3_time_series.md
      - Exponential Smoothing: manual/ExponentialSmoothing.md
      - Learning Curves Models: manual/LearningCurves.md
  - Tutorial:
    - Quick Start Guide: tutorials/1_first_model.md
    - Basic Model with Correlation: tutorials/2_Correlated_Model.md
    - Simulated Time Series: tutorials/3_NPV_testmodel.md

