name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: ['1.6', '1.8', '1.10', '1.11']

    steps:
      - uses: actions/checkout@v3

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}

      - name: Install Dependencies
        run: |
          julia --project=. -e '
            using Pkg;
            Pkg.develop(path=".");  # In case it's not registered
            Pkg.instantiate();
          '

      - name: Run Tests
        run: |
          julia --project=. -e '
            using Pkg;
            Pkg.test()
          '

      - name: Show Julia and package status (for debugging)
        run: |
          julia --project=. -e '
            using InteractiveUtils, Pkg;
            versioninfo();
            Pkg.status()
          '
