name: TagBot
on:
  issue_comment:
    types:
      - created
  workflow_dispatch:
jobs:
  set_git_identity:
    name: Set Git identity
    runs-on: ubuntu-latest
    steps:
      - run: |
          git config --global user.name "Eric Torkia"
          git config --global user.email "etorkia@technologypartnerz.com"
  TagBot:
    if: github.event_name == 'workflow_dispatch' || github.actor == 'JuliaTagBot'
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}